### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by Kuperus** [gurrhack/NetHack-Android#64]
Game crashes while starting:

Unknown error while preparing content.
Any idea what i can do?

**Comment by gurrhack** [comment]
Are you running Android 11? It's not supported yet.

**Comment by Kuperus** [comment]
Yep running 11, any idea if it will be supported?

**Comment by gurrhack** [comment]
Yes, it will be. The bug is fixed but it doesn't support updating from an old version at the moment. If you don't mind losing your game data you can [try this version](https://github.com/gurrhack/NetHack-Android/releases/tag/v3.6.6-2-unstable).

**Comment by Kuperus** [comment]
i don`t have any previous data, fresh install :) i`ll give it a whirl :)

**Comment by dacconcio** [comment]
@gurrhack I'm still getting this error on startup with Android 11 after deleting and reinstalling. Anything else I can try? I'm using a Pixel 4. Thanks for creating this app.

**Comment by mbonastre** [comment]
If it is of any help:

Google Play version (gurr's Nethack 3.6.2; updated 19-05-2019):
 - Works fine on Samsung Galaxy A70 with Android 11 (updated to 01-april-2021)
 - Fails on Samsung Galaxy Tab S7 with Android 11 (updated to 01-may-2021)

Version 3.6.6-2 unstable works fine on the tablet.

**Comment by lenzp** [comment]
Same problem here: Galaxy A40, Andoid 11 from 1st August 2021

The latest version of Nethack worked very well. Then suddenly during a game, since one day, all text messages are shown in very small letters if I hold my phone in portrait orientation. If I turn it by 90° in landscape orientation, all messages are shown in normal letters. If I turn it back to portrait orientation, there is no wordwrap anymore, and the same message layout is squeezed into the shorter dimension of the screen, that's why the phone uses very small letters. See screenshot.

Yesterday I ascended and started a new game: same bug.
Today I deleted it and installed a completely new version: CRASH.
I can only hope that my description above helps to find the reason for the crashes.
![Screenshot_20211018-182616](https://user-images.githubusercontent.com/50932693/139497719-f03f4fd7-d529-4a77-9262-aadd8eb6e9a4.jpg)

**Comment by lenzp** [comment]
Today I installed 3.6.6-2 unstable. Seems to work so far.

**Comment by scheriam** [comment]
tested startup successfully on 3.6.6-2 unstable on a Samsung Galaxy A52 with Android 12! With the App-Store version I observed the described bug on the same device.
